################################################################################################
#   Copyright (c) Rowe Wilson Frederisk Holme. All rights reserved.
#   Licensed under the MIT License. See License.txt in the project root for license information.
################################################################################################
---
version: 3.1.{build}
image: Visual Studio 2019
environment:
  matrix:
    # - nodejs_version: "10" # Node.js 10 has been deprecated since May 2020
    # - nodejs_version: "12" # Node.js 12 has been deprecated since Oct 2020
    # - nodejs_version: "14" # Node.js 14 has been deprecated since Oct 2021
    # - nodejs_version: "15" # Node.js 15 has been deprecated since Apr 2021
    - nodejs_version: "16"
    - nodejs_version: "18"
matrix:
  allow_failures:
    - nodejs_version: "18"
# init:
#   - sh: export DISPLAY=':99.0'
#   - sh: /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
install:
  - ps: Install-Product node $env:nodejs_version
build_script:
  - npm install yarn -g
  - yarn
  - yarn run compile
test_script:
  - npm run test
notifications:
  - provider: Email
    to:
      - frederisk@outlook.com
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true
